const ALLOWED_ORIGINS=new Set(['https://xconflictionx.cc','https://www.xconflictionx.cc']);
const cors=o=>({'Access-Control-Allow-Origin':ALLOWED_ORIGINS.has(o)?o:'https://xconflictionx.cc','Access-Control-Allow-Methods':'POST, OPTIONS','Access-Control-Allow-Headers':'Content-Type','Vary':'Origin'});
const out=(x,s=200,o='')=>new Response(JSON.stringify(x),{status:s,headers:{...cors(o),'Content-Type':'application/json','Cache-Control':'no-store'}});
const clamp=n=>Math.max(0,Math.min(100,Math.round(n)));
const grade=n=>n>=95?'A+':n>=90?'A':n>=85?'A-':n>=80?'B+':n>=75?'B':n>=70?'B-':n>=65?'C+':n>=60?'C':n>=55?'C-':n>=50?'D':'F';
const first=(s,r)=>{const m=s.match(r);return m?(m[1]||'').trim():''};
const all=(s,r)=>{const a=[];let m;while((m=r.exec(s)))a.push(m[1]||'');return a};
const attr=(t,n)=>first(t,new RegExp("\\b"+n+"\\s*=\\s*[\"']([^\"']*)[\"']","i"));
const abs=(v,b)=>{try{return new URL(v,b).href}catch{return null}};
const host=u=>{try{return new URL(u).hostname.toLowerCase()}catch{return ''}};
const text=s=>s.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,' ').replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();
async function target(u){const x=new URL(u);if(!/^https?:$/.test(x.protocol)||x.username||x.password)throw Error('Only public HTTP/HTTPS URLs are allowed.');const h=x.hostname.toLowerCase();if(/^(localhost|127\.|10\.|192\.168\.|169\.254\.)/.test(h)||h.endsWith('.local'))throw Error('Private/local targets are not allowed.');return x.href}
async function get(start,accept='*/*'){let u=start,chain=[];for(let i=0;i<8;i++){const r=await fetch(u,{redirect:'manual',headers:{'User-Agent':'SiteGrade/2.0 (+https://xconflictionx.cc/tools/)','Accept':accept}});const l=r.headers.get('location');if(r.status>=300&&r.status<400&&l){u=new URL(l,u).href;chain.push({status:r.status,to:u});continue}return{r,u,chain}}throw Error('Too many redirects.')}
function add(a,severity,category,title,detail,evidence=''){a.push({severity,category,title,detail,evidence})}
async function scan(input){const started=Date.now(),u=await target(input),p=await get(u,'text/html,application/xhtml+xml,*/*'),r=p.r;if(!r.ok)throw Error(`Target returned HTTP ${r.status}.`);const html=await r.text(),h=Object.fromEntries(r.headers),f=[];
const title=first(html,/<title\b[^>]*>([\s\S]*?)<\/title>/i).replace(/\s+/g,' '),desc=first(html,/<meta\b[^>]*name=["']description["'][^>]*content=["']([^"']*)["']/i),canon=first(html,/<link\b[^>]*rel=["'][^"']*canonical[^"']*["'][^>]*href=["']([^"']*)["']/i),h1=all(html,/<h1\b[^>]*>([\s\S]*?)<\/h1>/gi).map(text),links=all(html,/<a\b[^>]*href=["']([^"']+)["']/gi).map(x=>abs(x,p.u)).filter(Boolean);
let security=100;if(!h['strict-transport-security']){security-=12;add(f,'medium','security','Missing HSTS','Strict-Transport-Security was not detected.')}if(!h['content-security-policy']){security-=12;add(f,'medium','security','Missing Content-Security-Policy','No Content-Security-Policy response header was detected.')}else if(/unsafe-inline|unsafe-eval/i.test(h['content-security-policy'])){security-=5;add(f,'low','security','Permissive Content-Security-Policy','The CSP permits unsafe inline/eval behavior.',h['content-security-policy'])}for(const [k,n,t,d] of [['x-content-type-options',7,'Missing X-Content-Type-Options','Add nosniff.'],['x-frame-options',5,'Missing X-Frame-Options','Protect against unwanted framing.'],['referrer-policy',5,'Missing Referrer-Policy','Declare a deliberate referrer policy.'],['permissions-policy',5,'Missing Permissions-Policy','Restrict unused browser features.']])if(!h[k]){security-=n;add(f,'medium','security',t,d)}if(h.server)add(f,'info','security','Server header disclosed','A Server response header is exposed.',h.server);
let seo=100;if(!title){seo-=15;add(f,'medium','seo','Missing page title','No title element was detected.')}else if(title.length<15||title.length>60){seo-=6;add(f,'low','seo','Title length could improve',`The title is ${title.length} characters.`,title)}if(!desc){seo-=8;add(f,'medium','seo','Missing meta description','No meta description was detected.')}if(!canon){seo-=5;add(f,'low','seo','Canonical URL not detected','No canonical link was detected.')}if(!h1.length){seo-=8;add(f,'medium','seo','Missing H1','No H1 heading was detected.')}else if(h1.length>1){seo-=3;add(f,'low','seo','Multiple H1 headings',`${h1.length} H1 headings were detected.`)}if(!/<meta\b[^>]*property=["']og:title/i.test(html))add(f,'info','seo','No Open Graph title','og:title was not detected.');if(!/application\/ld\+json/i.test(html))add(f,'info','seo','No JSON-LD structured data','Structured data was not detected.');
let privacy=100;const cookies=(r.headers.get('set-cookie')||'').split(/,(?=\s*[^;,=]+\s*=)/).filter(Boolean);for(const c of cookies){const n=c.split('=')[0];if(!/;\s*secure/i.test(c)){privacy-=10;add(f,'medium','privacy',`Cookie "${n}" lacks Secure`,'The cookie is not marked Secure.')}if(!/;\s*httponly/i.test(c)){privacy-=5;add(f,'low','privacy',`Cookie "${n}" lacks HttpOnly`,'The cookie is readable by client-side JavaScript.')}if(!/samesite=/i.test(c)){privacy-=4;add(f,'low','privacy',`Cookie "${n}" has no SameSite`,'SameSite is not explicitly declared.')}}
const resource=all(html,/<(?:script|img|iframe|link|source)\b[^>]*(?:src|href)=["']([^"']+)["']/gi).map(x=>abs(x,p.u)).filter(Boolean),third=[...new Set(resource.map(host).filter(x=>x&&x!==host(p.u)))];if(third.length>5)add(f,'low','privacy','Many third-party origins',`${third.length} external origins were referenced.`);
let perf=100;const bytes=new TextEncoder().encode(html).length,elapsed=Date.now()-started;if(elapsed>1500){perf-=15;add(f,'medium','performance','Slow initial response',`${elapsed} ms observed before the scan completed.`)}else if(elapsed>800){perf-=7;add(f,'low','performance','Response could be faster',`${elapsed} ms observed before the scan completed.`)}if(bytes>500000){perf-=10;add(f,'medium','performance','Large HTML response',`${(bytes/1024/1024).toFixed(2)} MiB of HTML.`)}if(!h['content-encoding']&&bytes>20000){perf-=6;add(f,'low','performance','No response compression detected','No gzip/Brotli content encoding was advertised.')}const rb=(html.match(/<script\b(?![^>]*\b(?:async|defer)\b)[^>]*\bsrc=/gi)||[]).length;if(rb>3){perf-=5;add(f,'low','performance','Render-blocking scripts',`${rb} external scripts lack async/defer.`)}
let acc=100;const imgs=html.match(/<img\b[^>]*>/gi)||[],missing=imgs.filter(t=>!attr(t,'alt')).length;if(!/<html\b[^>]*\blang=/i.test(html)){acc-=10;add(f,'medium','accessibility','Missing HTML language','The html element has no lang attribute.')}if(missing){acc-=Math.min(15,missing*3);add(f,'medium','accessibility','Images missing alt text',`${missing} image(s) lack alt text.`)}if(!/<main\b/i.test(html)){acc-=5;add(f,'low','accessibility','No main landmark','No main element was detected.')}
let config=100;const base=new URL(p.u).origin;for(const [path,label] of [['/robots.txt','Robots.txt'],['/sitemap.xml','Sitemap']]){try{const q=await get(base+path);if(!q.r.ok){config-=4;add(f,'low','configuration',`${label} not found`,`${path} returned HTTP ${q.r.status}.`)}}catch{add(f,'info','configuration',`${label} could not be checked`,`Unable to retrieve ${path}.`)}}for(const path of ['/.env','/.git/config']){try{const q=await get(base+path);if(q.r.ok){config-=20;add(f,'high','configuration',`Potentially exposed ${path}`,'The public URL returned a successful response.')}}catch{}}
let dns={A:[],AAAA:[],CNAME:[],MX:[],NS:[]};for(const type of Object.keys(dns))try{const q=await fetch(`https://cloudflare-dns.com/dns-query?name=${encodeURIComponent(host(p.u))}&type=${type}`,{headers:{Accept:'application/dns-json'}});dns[type]=((await q.json()).Answer||[]).map(x=>x.data)}catch{}
const scores={security:clamp(security),privacy:clamp(privacy),performance:clamp(perf),seo:clamp(seo),configuration:clamp(config),accessibility:clamp(acc)},overall=clamp(scores.security*.25+scores.privacy*.12+scores.performance*.18+scores.seo*.18+scores.configuration*.15+scores.accessibility*.12);const rank={high:0,medium:1,low:2,info:3};f.sort((a,b)=>(rank[a.severity]??3)-(rank[b.severity]??3));return{ok:true,scannerVersion:'2.0',targetUrl:u,finalUrl:p.u,status:r.status,durationMs:Date.now()-started,overall:{score:overall,grade:grade(overall)},scores,findings:f,summary:`${f.filter(x=>x.severity!=='info').length} actionable finding(s) across six audit categories.`,page:{contentType:h['content-type']||'',htmlBytes:bytes,title,description:desc,canonical:canon||null,h1Count:h1.length,links:links.length,internalLinks:links.filter(x=>new URL(x).origin===new URL(p.u).origin).length,externalLinks:links.filter(x=>new URL(x).origin!==new URL(p.u).origin).length},privacy:{cookieCount:cookies.length,thirdPartyOrigins:third},performance:{ttfbMs:elapsed,htmlBytes:bytes,compression:h['content-encoding']||'none',renderBlockingScripts:rb,scriptCount:(html.match(/<script\b/gi)||[]).length,imageCount:imgs.length},accessibility:{imageCount:imgs.length,missingAlt:missing},configuration:{redirects:p.chain.length,robotsChecked:true,sitemapChecked:true},dns}}
export default{async fetch(req){const o=req.headers.get('Origin')||'';if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors(o)});const u=new URL(req.url);if(u.pathname==='/health')return out({ok:true,scannerVersion:'2.0'},200,o);if(u.pathname!=='/scan'||req.method!=='POST')return out({error:'Not found'},404,o);if(o&&!ALLOWED_ORIGINS.has(o))return out({error:'Origin not allowed'},403,o);try{const b=await req.json();if(!b?.url)return out({error:'Missing url'},400,o);return out(await scan(b.url.trim()),200,o)}catch(e){return out({error:e?.message||'Scan failed'},400,o)}}};
